# Generated by Django 4.0.3 on 2022-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65, verbose_name='余额'),
            preserve_default=False,
        ),
    ]
